### ISSUE TITLE
go_default_test and relay_test. are failing with Bazel@HEAD

### ISSUE THREAD

**Issue by sgowroji** [googlecloudrobotics/core#248]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3450#018bb6fa-68ba-4321-ac26-51ceac6b3af6

Platform : Ubuntu

Logs:
```
//src/go/tests:relay_test                                                FAILED in 3 out of 3 in 0.2s
//src/go/tests/apps:go_default_test                                      FAILED in 3 out of 3 in 201.5s
```

Steps:
```
git clone -v https://github.com/googlecloudrobotics/core.git
git reset d2d72cdc6887bb0314ac20da23135db5463d1479 --hard
export USE_BAZEL_VERSION=17be878292730359c9c90efdceabed26126df7ae
echo '
      CLOUD_ROBOTICS_CONTAINER_REGISTRY = "gcr.io/dummy"
      DOCKER_TAG = "latest"' > config.bzl
bazel test //...
```

CC Greenteam @Wyverald

**Comment by drigz** [comment]
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //src/go/tests:relay_test
-----------------------------------------------------------------------------
/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/31880e84a3606a7bbcde1b0f03f1bf5b/sandbox/linux-sandbox/2359/execroot/_main/bazel-out/k8-fastbuild/bin/src/go/tests/relay_test.runfiles/_main/src/go/tests/relay_test: line 54: kubectl: command not found
/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/31880e84a3606a7bbcde1b0f03f1bf5b/sandbox/linux-sandbox/2359/execroot/_main/bazel-out/k8-fastbuild/bin/src/go/tests/relay_test.runfiles/_main/src/go/tests/relay_test: line 56: kubectl: command not found
/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/31880e84a3606a7bbcde1b0f03f1bf5b/sandbox/linux-sandbox/2359/execroot/_main/bazel-out/k8-fastbuild/bin/src/go/tests/relay_test.runfiles/_main/src/go/tests/relay_test: line 57: kubectl: command not found
Checking relay is working...
/var/lib/buildkite-agent/.cache/bazel/_bazel_buildkite-agent/31880e84a3606a7bbcde1b0f03f1bf5b/sandbox/linux-sandbox/2359/execroot/_main/bazel-out/k8-fastbuild/bin/src/go/tests/relay_test.runfiles/_main/src/go/tests/relay_test: line 59: kubectl: command not found
TEST FAILED: during setup, failed to reach the robot-sim VM
```

@ensonic Should we just remove CRC from the Bazel CI? Now we're using GitHub actions it seems unnecessary.

**Comment by sgowroji** [comment]
Hi @ensonic, Did you get a chance to check the above issue. Thanks!

**Comment by ensonic** [comment]
Yes, we've already bump the go version to address some of the issues. But the tests are still failing:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3464#018bd649-e931-499e-9e94-90d92a97bf21

src/go/tests/relay_test
https://buildkite.com/organizations/bazel/pipelines/bazel-at-head-plus-downstream/builds/3464/jobs/018bd649-e931-499e-9e94-90d92a97bf21/artifacts/018bd64b-e003-4e00-88d4-25a9901cf67b

fails due to "src/go/tests/relay_test: line 59: kubectl: command not found"

src/go/tests/go_default_test
https://buildkite.com/organizations/bazel/pipelines/bazel-at-head-plus-downstream/builds/3464/jobs/018bd649-e931-499e-9e94-90d92a97bf21/artifacts/018bd64b-f106-45d0-af0d-6ff1ad2572a6

crashes "Failed to create kubernetes client: must provide non-nil rest.Config to client.New"

We'll take a look at these to as soon as we're able to

**Comment by ensonic** [comment]
@drigz shall we just tag both tests "manual" (in addition to external)?

**Comment by drigz** [comment]
sure, will send a change

**Comment by sgowroji** [comment]
Gentle remainder, Any update on the above issue?

**Comment by drigz** [comment]
Hey, apologies for not following up here. I sent https://github.com/googlecloudrobotics/core/pull/251 - does that address the issue on your side? If not, please let us know what the steps are to get this repo removed from Buildkite are.

**Comment by sgowroji** [comment]
Thanks for the update. CI turned green. We can close this issue now.
