### ISSUE TITLE
install_k8s_on_robot.sh Failed: Error: Failed to install docker E: Version '5:20.10.6~3-0~ubuntu-focal' for 'docker-ce' was not found 

### ISSUE THREAD

**Issue by tiesus** [googlecloudrobotics/core#319]
When install the cluster on the robot via `install_k8s_on_robot.sh` i get the following error due to a missmatch of the docker versions:

`E:_ Version '5:20.10.6~3-0~ubuntu-focal' for 'docker-ce' was not found
ERROR: Failed to install docker-ce=5:20.10.6~3-0~ubuntu-focal. Try:
    sudo apt update && sudo apt install docker-ce=5:20.10.6~3-0~ubuntu-focal `

My docker version on the device is **24.0.5.** Is it really necessary to stick to the docker version, you require in the script?

**Comment by drigz** [comment]
It appears the script is quite obsolete. Even if we lift the docker pin it will try to install k8s 1.21, which is likely to fail. A few years ago it served as a useful example to get started with a local k8s cluster, but now it's more trouble than it's worth. We ought to remove the obsolete script and the docs that point at it but I'm not quite sure how to replace them.

You could try other lightweight k8s distros like k3s or k0s as they will probably work better on your device - sorry that I can't point you at more up-to-date instructions!

**Comment by drigz** [comment]
Note for readers: GitHub generates the text "closed as completed" but this is actually "closed as obsolete" because we deleted the script and changed the docs to say "set up your own cluster". That said, I'm not optimistic that someone could follow the docs as we haven't tested this end to end and there might be some config incompatibilities between the user cluster and our installation that we haven't documented how to resolve, in particular I'm thinking about the --pod-cidr flag: https://github.com/googlecloudrobotics/core/blob/8a86fa6bbfb8afc547fe4b2b28ceab9b71b0ad84/src/go/cmd/setup-robot/main.go#L60
