### ISSUE TITLE
Using k3s in google cloud robotics

### ISSUE THREAD

**Issue by TommyLike** [googlecloudrobotics/core#6]
It seems that **K3S** is a great version for IOT and Edge scenario, will google cloud robotics will use this in project?

**Comment by drigz** [comment]
We've had a look, and it addresses some important points like network security and memory use. However, since it's quite a young project, we'll wait to see how it develops, especially regarding etcd support and new Kubernetes versions.

We'd need to know a bit more about the following first - perhaps you could answer these questions if you know the technical details of k3s.

- Does the k3s sqlite backend support K8s custom resources?
- Is Helm fully compatible with K3s clusters?

**Comment by TommyLike** [comment]
Oh, neither do I, just curious:)
